# Generated by Django 4.2.2 on 2023-06-24 15:11

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_profiles',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hospital Profile',
            },
        ),
    ]
