# Generated by Django 3.2.19 on 2023-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0004_alter_all_profiles_id'),
        ('victims', '0005_auto_20230623_2209'),
    ]

    operations = [
    ]
