# Generated by Django 3.2.19 on 2023-06-25 14:45

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0006_merge_20230624_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='victims/images'),
        ),
        migrations.AlterField(
            model_name='all_profiles',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
