# Generated by Django 3.2.19 on 2023-06-25 15:10

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0007_auto_20230625_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_profiles',
            name='Image',
        ),
        migrations.AlterField(
            model_name='all_profiles',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='victims/images')),
                ('all_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.all_profiles')),
            ],
        ),
        migrations.AddField(
            model_name='all_profiles',
            name='images',
            field=models.ManyToManyField(related_name='victims', to='victims.Image'),
        ),
    ]
