# Generated by Django 3.2.19 on 2023-09-08 14:29

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0012_auto_20230628_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_profiles',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='all_profiles',
            name='ngo_assigned',
            field=models.CharField(blank=True, choices=[('GodGivenHomes', 'GodGivenHomes'), ('KKGP', 'KKGP'), ('HPC Homes', 'HPC Homes'), ('Homes4U', 'Homes4U')], default='', max_length=100),
        ),
    ]
